language: python
# linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
matrix:
  include:      
    # windows
    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
        - pip3 install -r requirements/requirements_win.txt
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
        - pip3 install -r requirements/requirements_win.txt
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - sudo apt-get update
  - sudo apt-get -y install libglib2.0-dev libdbus-1-3 libdbus-1-dev
  - pip install -r requirements/requirements_other.txt
script: pytest
after_success:
  - codecov